### ISSUE TITLE
Basic electric mining drill missing

### ISSUE THREAD

**Issue by d64d64** [LovelySanta/FactorioMod-MoreScience#22]
Apologies if this is not the preferred channel to file issues. I just started a game with 0.17, Bob's, Angel's, some other mods and Morescience + the addons. I notice that electric mining drill recipe is not available. In FNEI, the icon is there but it cannot be clicked. Drill mk2 is there but a basic drill is one of the ingredients. I tried disabling Morescience mods, after which the drill recipe reappears. It's quite possible I'm missing some mod or I have some mod that is not compatible, here is the list: https://pastebin.com/P5kFEBeq . All should be in their latest versions.

**Comment by LovelySanta** [comment]
Thanks for the report, I'll look into it.

**Comment by LovelySanta** [comment]
Fixed, please update the BobAngelExtension (v0.2.4)
