### ISSUE TITLE
With ScienceCostTweakerM, basic lab parts cannot be built

### ISSUE THREAD

**Issue by d64d64** [LovelySanta/FactorioMod-MoreScience#23]
With Bob's, Angel's, MoreScience and ScienceCostTweakerM it seems impossible to build the first type of lab. "Electromagnetism lab burner" requires "Lab construction core" and "Lab mechanization", but these are gated behind the "Electromagnetism lab" tech - the 2nd type of lab in the tree. The lab recipe itself is available but these reagents are not. I am not 100% sure this is a MoreScience bug, but disabling MoreScience mods resulted in the recipe being usable again. Here is my modlist: https://pastebin.com/w6BJ7ZC5 .

**Comment by LovelySanta** [comment]
I see the issue, it's the same issue as I had with #22 where Bob is creating a tech with the exact same name of mine. I'll get a hotfix up for SCT as well.

**Comment by LovelySanta** [comment]
Fixed, please update the SCTextension (v0.2.3)
