### ISSUE TITLE
Possible typo in electromagnetism lab research cost

### ISSUE THREAD

**Issue by d64d64** [LovelySanta/FactorioMod-MoreScience#24]
More minor issue: again with Bob's, Angel's, SCT and More Science. All techs requiring only red science have a cost of 1 * X, except for Electromagnetism lab which has a cost of 10 * 15. I suspect this could be a typo, considering the next tier of lab has a cost of only 1 * 30. Just filing this in case it is not intended. I tried disabling MoreScience mods again, and found the recipe is not in the tree without them.

**Comment by LovelySanta** [comment]
It is indeed [a typo](https://github.com/LovelySanta/FactorioMod-MoreScience-ScienceCostTweakerExtension/blob/c4da902de63f70bda42e74175e247fc257c199dd/prototypes/technology/research-labs.lua#L15). I'll fix this, but as this is not a game breaking bug, I won't put out a release for this small bug alone.

**Comment by LovelySanta** [comment]
If you want to fix this for yourself in the meantime, you have to change 1 line of code in the SCT extension:
![image](https://user-images.githubusercontent.com/26593477/61991926-9fbb3400-b057-11e9-82dd-c5f93294501b.png)
Kind regards
lovely_santa

**Comment by d64d64** [comment]
Yes, this is not game breaking, it just took 20 mins to make the extra bottles. Thanks.
