### ISSUE TITLE
Followup from mod portal

### ISSUE THREAD

**Issue by ianjirka** [LovelySanta/FactorioMod-MoreScience#25]
Following up on this discussion - attaching a minimal repro for you.  I think the 'Burner Power Phase' setting is the key.

https://mods.factorio.com/mod/MoreScience/discussion/5d40ed34583730000d50cbc7
[Repro.zip](https://github.com/LovelySanta/FactorioMod-MoreScience/files/3464450/Repro.zip)

**Comment by LovelySanta** [comment]
Thanks, I see the issue

Bob is adding a new technology to unlock the red science pack, but with the wrong recipe. I'm gonna merge this new tech with the one SCT creates, so it is 1 tech with the steam science packs.

This way, you research red science with the steam science pack (the one without fluids) and from there you can research the chemical plant as before:

![image](https://user-images.githubusercontent.com/26593477/62420998-850e3e00-b69b-11e9-9646-9c499a2edfdb.png)

And from there on you're well on your way on researching the fluid recipe:

![image](https://user-images.githubusercontent.com/26593477/62421010-9fe0b280-b69b-11e9-8f07-9db4379d4941.png)

**Comment by ianjirka** [comment]
Thanks!  BTW I worked around it with a small patch this way.

bobmods.lib.tech.remove_recipe_unlock("automation-science-pack", "automation-science-pack");
bobmods.lib.tech.add_recipe_unlock("automation-science-pack", "automation-science-pack-basic");
bobmods.lib.tech.add_prerequisite("sct-automation-science-pack", "bottling-research")

Either approach works fine, I think.

**Comment by LovelySanta** [comment]
I took this approach:

- When playing with SCT (without bobs/angels):
    - Nothing changes
- When playing with bobs/angels (without SCT) + bobs burner phase
    - Unlock red science through the bobs automation science pack technology.
        - Swapped out the recipe unlocks as you described, to unlock the basic recipe instead of the fluid version.
        - Lock the basic red science pack so it is unlocked by researching it
    - All research requiring red science is locked behind this bob automation science technology
- When playing with bobs/angels and SCT + bobs burner phase
    - Now there are 2 researched that unlock the basic red science bottle. I've merged everything into the one from bobtech:
        - The prerequisites from SCT's red science are now added to bobs red science tech
        - All techs depending on SCT's red science are now depending on  bobs red science tech
        - Hide SCT's red science research as it is now obsolete

Now this is fixed, will be part of the next release. You'll have to update both bobs angels and SCT extensions.

Kind regards
lovely_santa
